name: Test eslint is executed correctly

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Check eslint works
        run: yarn test